[package]

name = "jitrust"
version = "0.0.1"
authors = [ "Stanislav Pankevich <s.pankevich@gmail.com>" ]

[lib]
name = "jitrust"
path = "jitrust.rs"
test = true
doctest = false

[dev-dependencies]
# tempdir = "*"

